### Fase 0: Lectura y exploración inicial

Abrir terminal y copiar, pegar y ejecutar por separado:
pip install pandas
pip install numpy
pip install matplotlib
pip install seaborn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv('../Data/Telco-Customer-Churn.csv')      
display(df)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [14]:
print("\n--- HEAD DEL DATASET ---")
display(df.head())

print("\n--- INFORMACIÓN GENERAL ---")
df.info()

print("\n--- ESTADÍSTICAS DESCRIPTIVAS NUMÉRICAS ---")
display(df.describe())

print("\n--- ESTADÍSTICAS COMPLETAS ---")
display(df.describe(include='all'))

print("\n--- DIMENSIONES DEL DATASET ---")
display(df.shape)

print("\n--- NOMBRES DE COLUMNAS ---")
display(df.columns.to_list())

--- HEAD DEL DATASET ---

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

--- INFORMACIÓN GENERAL ---
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

--- ESTADÍSTICAS DESCRIPTIVAS NUMÉRICAS ---

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

--- ESTADÍSTICAS COMPLETAS ---

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,7590-VHVEG,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

--- DIMENSIONES DEL DATASET ---

(7043, 21)

--- NOMBRES DE COLUMNAS ---

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

Diccionario de Datos

| Campo            | Descripción                                                                        |
| ---------------- | ---------------------------------------------------------------------------------- |
| customerID       | Identificador único del cliente.                                                   |
| gender           | Género del cliente (Male/Female).                                                  |
| SeniorCitizen    | Indica si el cliente es mayor de 65 años (0 = No, 1 = Sí).                         |
| Partner          | Indica si el cliente tiene pareja (Yes/No).                                        |
| Dependents       | Indica si el cliente tiene dependientes económicos (Yes/No).                                  |
| tenure           | Número de meses que el cliente ha permanecido en la compañía.                      |
| PhoneService     | Indica si el cliente tiene servicio telefónico (Yes/No).                           |
| MultipleLines    | Indica si el cliente tiene múltiples líneas telefónicas (Yes/No/No phone service). |
| InternetService  | Tipo de servicio de internet (DSL, Fiber optic, No).                               |
| OnlineSecurity   | Indica si el cliente tiene seguridad en línea (Yes/No/No internet service).        |
| OnlineBackup     | Indica si el cliente tiene backup en línea (Yes/No/No internet service).           |
| DeviceProtection | Indica si el cliente tiene protección de dispositivo (Yes/No/No internet service). |
| TechSupport      | Indica si el cliente tiene soporte técnico (Yes/No/No internet service).           |
| StreamingTV      | Indica si el cliente tiene streaming de TV (Yes/No/No internet service).           |
| StreamingMovies  | Indica si el cliente tiene streaming de películas (Yes/No/No internet service).    |
| Contract         | Tipo de contrato (Month-to-month, One year, Two year).                             |
| PaperlessBilling | Indica si el cliente tiene facturación sin papel (Yes/No).                         |
| PaymentMethod    | Método de pago (Electronic check, Mailed check, Bank transfer, Credit card).       |
| MonthlyCharges   | Monto facturado mensualmente al cliente.                                           |
| TotalCharges     | Monto total facturado al cliente durante su permanencia.                           |
| Churn            | Indica si el cliente abandonó el servicio (Yes/No).                                |

### FASE 1: Limpieza de Datos (Data Cleaning)

1.1 Eliminar customerID

Este código elimina la columna customerID del dataset. Esta variable corresponde a un identificador único de cada cliente y no aporta información útil para el modelo de predicción. Mantenerla podría generar ruido en el entrenamiento de la inteligencia artificial, ya que el modelo podría intentar encontrar patrones en valores aleatorios.

In [15]:
print("\n--- ELIMINAR COLUMNA customerID ---")
df = df.drop("customerID", axis=1)
display(df.head())

--- ELIMINAR COLUMNA customerID ---

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

La limpieza de datos fue realizada correctamente. La columna customerID ya no aparece en el dataset, lo que confirma que fue eliminada exitosamente. Este paso es importante porque los identificadores únicos no aportan valor predictivo al modelo de inteligencia artificial y podrían introducir ruido durante el entrenamiento.

Al revisar el head() del dataframe, se observa que ahora solamente permanecen las variables relevantes para el análisis del churn, incluyendo datos demográficos, servicios contratados, facturación y la variable objetivo Churn.

1.2 Corregir tipo de dato de TotalCharges
Este código convierte la columna TotalCharges desde tipo texto (object) a tipo numérico (float). Esto es necesario porque la columna contiene valores que parecen números, pero fueron interpretados como texto al cargar el CSV. Además, se utiliza errors='coerce' para transformar valores vacíos o inválidos en NaN, permitiendo detectar datos faltantes ocultos.

In [16]:
print("\n--- CORREGIR TIPO DE DATO DE TotalCharges ---")
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
print("\nTipo de dato actual:")
print(df["TotalCharges"].dtype)
print("\nPrimeros valores de TotalCharges:")
display(df["TotalCharges"].head())

--- CORREGIR TIPO DE DATO DE TotalCharges ---

Tipo de dato actual:
float64

Primeros valores de TotalCharges:

0      29.85
1    1889.50
2     108.15
3    1840.75
4     151.65
Name: TotalCharges, dtype: float64

La conversión de la columna TotalCharges fue realizada correctamente. El tipo de dato cambió exitosamente a float64, lo que confirma que ahora los valores pueden ser utilizados en operaciones matemáticas, análisis estadísticos y modelos de Machine Learning.

Además, los primeros registros muestran valores numéricos válidos, indicando que la columna ya se encuentra en un formato adecuado para continuar con el procesamiento de datos. Hasta este punto no se observan valores NaN en los primeros registros visualizados, aunque aún es necesario verificar si existen datos faltantes en otras filas del dataset.

1.3 Manejo de valores nulos

Este código revisa la cantidad de valores nulos presentes en cada columna del dataset. Luego, reemplaza los posibles valores faltantes (NaN) de la columna TotalCharges por 0, evitando problemas durante el entrenamiento de modelos de inteligencia artificial.

In [20]:
print("\n--- REVISIÓN DE VALORES NULOS ---")
display(df.isnull().sum())

--- REVISIÓN DE VALORES NULOS ---

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
print("\n--- REEMPLAZAR VALORES NULOS EN TotalCharges ---") # habian 11 nulos en TotalCharges
df["TotalCharges"] = df["TotalCharges"].fillna(0)
print("\n--- REVISIÓN FINAL DE NULOS ---")
display(df.isnull().sum())

--- REEMPLAZAR VALORES NULOS EN TotalCharges ---

--- REVISIÓN FINAL DE NULOS ---

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

La revisión de valores nulos permitió identificar 11 registros vacíos en la columna TotalCharges. Estos valores faltantes fueron reemplazados exitosamente por 0 utilizando fillna(0).

Después de la limpieza, el dataset quedó completamente libre de valores nulos en todas sus columnas, lo que garantiza una mejor calidad de los datos para las siguientes etapas del proyecto. Este paso es fundamental, ya que la mayoría de los algoritmos de Machine Learning no pueden trabajar correctamente con datos vacíos.